{"error":"req.get is not a function","level":"error","message":"Unexpected error during certificate validation","service":"certificate-validation","stack":"TypeError: req.get is not a function\n    at get (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/middleware/certificate-validation.js:34:22)\n    at Object.validateClientCertificate (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/tests/server-certificate-validation.test.js:99:7)\n    at Promise.then.completed (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/utils.js:231:10)\n    at _callCircusTest (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:252:3)\n    at _runTestsForDescribeBlock (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:126:9)\n    at _runTestsForDescribeBlock (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:121:9)\n    at _runTestsForDescribeBlock (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:121:9)\n    at run (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:71:3)\n    at runAndTransformResultsToJestFormat (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)\n    at jestAdapter (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)\n    at runTestInternal (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-runner/build/runTest.js:367:16)\n    at runTest (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-runner/build/runTest.js:444:34)\n    at Object.worker (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-runner/build/testWorker.js:106:12)","timestamp":"2025-08-15T07:55:28.889Z"}
{"error":"req.get is not a function","level":"error","message":"Unexpected error during certificate validation","service":"certificate-validation","stack":"TypeError: req.get is not a function\n    at get (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/middleware/certificate-validation.js:34:22)\n    at Object.validateClientCertificate (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/tests/server-certificate-validation.test.js:126:7)\n    at Promise.then.completed (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/utils.js:231:10)\n    at _callCircusTest (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:252:3)\n    at _runTestsForDescribeBlock (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:126:9)\n    at _runTestsForDescribeBlock (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:121:9)\n    at _runTestsForDescribeBlock (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:121:9)\n    at run (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:71:3)\n    at runAndTransformResultsToJestFormat (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)\n    at jestAdapter (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)\n    at runTestInternal (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-runner/build/runTest.js:367:16)\n    at runTest (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-runner/build/runTest.js:444:34)\n    at Object.worker (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-runner/build/testWorker.js:106:12)","timestamp":"2025-08-15T07:55:28.894Z"}
{"error":"req.get is not a function","level":"error","message":"Unexpected error during certificate validation","service":"certificate-validation","stack":"TypeError: req.get is not a function\n    at get (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/middleware/certificate-validation.js:34:22)\n    at Object.validateClientCertificate (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/tests/server-certificate-validation.test.js:165:7)\n    at Promise.then.completed (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/utils.js:231:10)\n    at _callCircusTest (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:252:3)\n    at _runTestsForDescribeBlock (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:126:9)\n    at _runTestsForDescribeBlock (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:121:9)\n    at _runTestsForDescribeBlock (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:121:9)\n    at run (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:71:3)\n    at runAndTransformResultsToJestFormat (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)\n    at jestAdapter (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)\n    at runTestInternal (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-runner/build/runTest.js:367:16)\n    at runTest (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-runner/build/runTest.js:444:34)\n    at Object.worker (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-runner/build/testWorker.js:106:12)","timestamp":"2025-08-15T07:55:28.895Z"}
{"error":"req.get is not a function","level":"error","message":"Unexpected error during certificate validation","service":"certificate-validation","stack":"TypeError: req.get is not a function\n    at get (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/middleware/certificate-validation.js:34:22)\n    at Object.validateClientCertificate (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/tests/server-certificate-validation.test.js:197:7)\n    at Promise.then.completed (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/utils.js:231:10)\n    at _callCircusTest (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:252:3)\n    at _runTestsForDescribeBlock (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:126:9)\n    at _runTestsForDescribeBlock (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:121:9)\n    at _runTestsForDescribeBlock (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:121:9)\n    at run (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:71:3)\n    at runAndTransformResultsToJestFormat (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)\n    at jestAdapter (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)\n    at runTestInternal (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-runner/build/runTest.js:367:16)\n    at runTest (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-runner/build/runTest.js:444:34)\n    at Object.worker (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-runner/build/testWorker.js:106:12)","timestamp":"2025-08-15T07:55:28.896Z"}
{"error":"req.get is not a function","level":"error","message":"Unexpected error during certificate validation","service":"certificate-validation","stack":"TypeError: req.get is not a function\n    at get (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/middleware/certificate-validation.js:34:22)\n    at Object.validateClientCertificate (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/tests/server-certificate-validation.test.js:230:7)\n    at Promise.then.completed (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/utils.js:231:10)\n    at _callCircusTest (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:252:3)\n    at _runTestsForDescribeBlock (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:126:9)\n    at _runTestsForDescribeBlock (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:121:9)\n    at _runTestsForDescribeBlock (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:121:9)\n    at run (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:71:3)\n    at runAndTransformResultsToJestFormat (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)\n    at jestAdapter (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)\n    at runTestInternal (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-runner/build/runTest.js:367:16)\n    at runTest (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-runner/build/runTest.js:444:34)\n    at Object.worker (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-runner/build/testWorker.js:106:12)","timestamp":"2025-08-15T07:55:28.897Z"}
{"error":"req.get is not a function","level":"error","message":"Unexpected error during certificate validation","service":"certificate-validation","stack":"TypeError: req.get is not a function\n    at get (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/middleware/certificate-validation.js:34:22)\n    at validateClientCertificate (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/tests/server-certificate-validation.test.js:306:9)\n    at Object.<anonymous> (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/expect/build/toThrowMatchers.js:74:11)\n    at Object.throwingMatcher [as toThrow] (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/expect/build/index.js:320:21)\n    at Object.toThrow (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/tests/server-certificate-validation.test.js:307:14)\n    at Promise.then.completed (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/utils.js:231:10)\n    at _callCircusTest (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:252:3)\n    at _runTestsForDescribeBlock (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:126:9)\n    at _runTestsForDescribeBlock (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:121:9)\n    at _runTestsForDescribeBlock (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:121:9)\n    at run (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/run.js:71:3)\n    at runAndTransformResultsToJestFormat (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)\n    at jestAdapter (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)\n    at runTestInternal (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-runner/build/runTest.js:367:16)\n    at runTest (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-runner/build/runTest.js:444:34)\n    at Object.worker (/Users/victor/Documents/workspace/Certificate-Based-Authentication-Demo/node_modules/jest-runner/build/testWorker.js:106:12)","timestamp":"2025-08-15T07:55:28.900Z"}
{"error":"Certificate parsing failed","level":"error","message":"Failed to get peer certificate","service":"certificate-validation","timestamp":"2025-08-15T07:56:51.340Z"}
{"error":"Certificate parsing failed","level":"error","message":"Failed to get peer certificate","service":"certificate-validation","timestamp":"2025-08-15T07:57:13.642Z"}
{"error":"Certificate parsing failed","level":"error","message":"Failed to get peer certificate","service":"certificate-validation","timestamp":"2025-08-15T07:58:06.925Z"}
{"error":"Certificate parsing failed","level":"error","message":"Failed to get peer certificate","service":"certificate-validation","timestamp":"2025-08-15T07:58:33.952Z"}
{"error":"Certificate parsing failed","level":"error","message":"Failed to get peer certificate","service":"certificate-validation","timestamp":"2025-08-15T08:00:59.667Z"}
{"error":"Certificate parsing failed","level":"error","message":"Failed to get peer certificate","service":"certificate-validation","timestamp":"2025-08-15T08:33:34.874Z"}
{"error":"Certificate parsing failed","level":"error","message":"Failed to get peer certificate","service":"certificate-validation","timestamp":"2025-08-15T08:33:47.355Z"}
{"error":"Certificate parsing failed","level":"error","message":"Failed to get peer certificate","service":"certificate-validation","timestamp":"2025-08-15T08:35:52.827Z"}
{"error":"Certificate parsing failed","level":"error","message":"Failed to get peer certificate","service":"certificate-validation","timestamp":"2025-08-15T08:37:17.928Z"}
{"error":"Certificate parsing failed","level":"error","message":"Failed to get peer certificate","service":"certificate-validation","timestamp":"2025-08-15T08:37:47.468Z"}
